apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: templates-collection
  description: A collection Software Templates for Backstage
spec:
  type: url
  targets:
    - templates/add-namespace/template.yaml
    - templates/create-persistent-volume/template.yaml
    - templates/create-rds-postgresql/template.yaml
    - templates/migrate-vm-openshift/template.yaml
    - templates/onboard-user/template.yaml
    - templates/run-ansible-job/template.yaml
