apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-namespace
  title: Add a Namespace
  description: Add a Namespace
  tags:
    - recommended
spec:
  owner: user1
  system: janus-idp
  type: service

  parameters:
    - title: Provide information about the existing component
      required:
        - orgName
      properties:
        orgName:
          title: Organization Name
          type: string

  steps:
    - id: sourceCodeTemplate
      name: Generating the Source Code Component
      action: fetch:plain
      input:
        url: https://www.google.com